# Generated by Django 5.1.7 on 2025-03-27 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedback_given', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'event feedback',
                'verbose_name_plural': 'event feedback',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='OrganizerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Optional comment on organizer performance', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_ratings', to='events.event', verbose_name='Event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Volunteer')),
            ],
            options={
                'verbose_name': 'organizer rating',
                'verbose_name_plural': 'organizer ratings',
                'ordering': ['-created_at'],
                'unique_together': {('volunteer', 'organizer', 'event')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Optional comment on volunteer performance', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_ratings', to='events.event', verbose_name='Event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Volunteer')),
            ],
            options={
                'verbose_name': 'volunteer rating',
                'verbose_name_plural': 'volunteer ratings',
                'ordering': ['-created_at'],
                'unique_together': {('organizer', 'volunteer', 'event')},
            },
        ),
    ]
